In [0]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [0]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [3]:
x = torch.empty(5, 3)
print(x)
# the empty tensor has garbage values

tensor([[4.0387e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


Construct a randomly initialized matrix:



In [4]:
x = torch.rand(5, 3)
print(x)

tensor([[0.4379, 0.4228, 0.0985],
        [0.6197, 0.8719, 0.0834],
        [0.4879, 0.4116, 0.8870],
        [0.6266, 0.8562, 0.2102],
        [0.3598, 0.9084, 0.5382]])


Construct a matrix filled zeros and of dtype long:



In [5]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [6]:
x = torch.zeros(5,3, dtype=torch.int16)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int16)


Construct a tensor directly from data:



In [7]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1973, -0.5299,  1.5809],
        [-0.2655, -0.0427, -2.3159],
        [-0.3639, -0.8464,  0.4429],
        [ 0.0214,  0.2906,  0.2815],
        [ 0.7719,  1.7484, -2.5321]])


Get its size:



In [9]:
x.size()

torch.Size([5, 3])

<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [10]:
y = torch.rand(5, 3)
print(x + y)

tensor([[-0.0291,  0.0730,  2.0268],
        [ 0.2174,  0.6480, -1.8185],
        [-0.2962, -0.5109,  1.4029],
        [ 0.8846,  0.6089,  0.3276],
        [ 1.2126,  2.1558, -2.3017]])


Addition: syntax 2



In [11]:
print(torch.add(x, y))

tensor([[-0.0291,  0.0730,  2.0268],
        [ 0.2174,  0.6480, -1.8185],
        [-0.2962, -0.5109,  1.4029],
        [ 0.8846,  0.6089,  0.3276],
        [ 1.2126,  2.1558, -2.3017]])


Addition: providing an output tensor as argument



In [12]:
result = torch.empty(5, 3)
# another way to add the tensors and save them in the result tensor
torch.add(x, y, out=result)
print(result)

tensor([[-0.0291,  0.0730,  2.0268],
        [ 0.2174,  0.6480, -1.8185],
        [-0.2962, -0.5109,  1.4029],
        [ 0.8846,  0.6089,  0.3276],
        [ 1.2126,  2.1558, -2.3017]])


Addition: in-place



In [13]:
# adds x to y
y.add_(x) # special operator suffix to performa operation inplace
print(y)

tensor([[-0.0291,  0.0730,  2.0268],
        [ 0.2174,  0.6480, -1.8185],
        [-0.2962, -0.5109,  1.4029],
        [ 0.8846,  0.6089,  0.3276],
        [ 1.2126,  2.1558, -2.3017]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [14]:
print(x[:, 1])

tensor([-0.5299, -0.0427, -0.8464,  0.2906,  1.7484])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6365])
-0.6364914178848267


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <http://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [21]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([0.3635], device='cuda:0')
tensor([0.3635], dtype=torch.float64)
